[package]
name = "horse-racing"
version = "1.0.0"
edition = "2021"

[dependencies]
casper-contract = "3.0.0"
casper-types = "3.0.0"

[[bin]]
name = "horse-racing"
path = "src/main.rs"
bench = false
doctest = false
test = false
